export { BaseParser } from './BaseParser';
export { RowParser } from './parsers/RowParser';
export { RowListParser } from './parsers/RowListParser';
export { ColParser } from './parsers/ColParser';
export { SwitchParser } from './parsers/SwitchParser';
export { CheckboxParser } from './parsers/CheckboxParser';
export { RadioParser } from './parsers/RadioParser';
export { ProgressParser } from './parsers/ProgressParser';
export { SliderParser } from './parsers/SliderParser';
export { SwiperParser } from './parsers/SwiperParser';
export { IconParser } from './parsers/IconParser';
export { TabsParser } from './parsers/TabsParser';
export { NoopParser } from './parsers/NoopParser';
export declare const parseWxTags: (nodes: any) => void;
