export { beautifyHtml, beautifyCss, beautifyJs } from './beautify';
export { prettifyJs } from './prettier';
export { filterPrefix, filterNpmScope } from './filter';
export { config, customConfig, defaultConfig } from './config';
export { xcxNodeCache, xcxNext } from './cache';
export { getText, getInnerHTML, getOuterHTML } from './dom-serializer';
export { dom } from './dom';
export { style } from './style';
export { exec } from './exec';
export { Global } from './global';
export { log, LogType, LogLevel } from './log';
export { md } from './md';
export { resolveDep } from './resolveDep';
export { resolveUsingComponents } from './resolveUsingComponents';
export { scriptAstUtil } from './scriptAstUtil';
export { WxAppTemplate } from './template';
export declare const ICONFONT_PATTERN: RegExp;
import * as tool from './tool';
export default tool;
